# Autogenerated wrapper script for gmime_jll for aarch64-apple-darwin
export libgmime

using Glib_jll
using Libiconv_jll
JLLWrappers.@generate_wrapper_header("gmime")
JLLWrappers.@declare_library_product(libgmime, "@rpath/libgmime-3.0.0.dylib")
function __init__()
    JLLWrappers.@generate_init_header(Glib_jll, Libiconv_jll)
    JLLWrappers.@init_library_product(
        libgmime,
        "lib/libgmime-3.0.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
